Social_Media_Clone/urls.py
from django.contrib import admin
from django.urls import path, include
from auth_app.views import landing, about_us
# ----------------------------------------------------
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name='landing-page'),
    path('about-us', about_us, name='about-us'),
    path('auth/', include('auth_app.urls')),
    path('profile/', include('profile_app.urls'))]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth_app/urls.py
from django.urls import path
from auth_app.views import (login_form, register_form, user_authentication, new_user,
                            logout_user, forgot_password, sending_otp, verify_otp, set_new_password, social)


urlpatterns = [
    path('login/', login_form, name='auth_app-login'),
    path('register/', register_form, name='auth_app-register'),
    path('user-authentication/', user_authentication, name='auth_app-user-authentication'),
    path('new-user/', new_user, name='auth_app-new-user'),
    path('logout/', logout_user, name='auth_app-logout'),
    path("forgot-password/", forgot_password, name='auth_app-forgot-password'),
    path("sending-otp/", sending_otp, name='auth_app-sending-otp'),
    path("verify-otp/", verify_otp, name="auth_app-verify-otp"),
    path("set-new-password/", set_new_password, name='auth_app-set-new-password'),
    path("social/", social, name='auth_app-sign-in-with-google')
]

profile_app/urls.py
from django.urls import path
from profile_app.views import (home, feeds, settings, update_profile, add_post, search_user,
                               follow_user, like_post, unfollow_user, delete_post)

urlpatterns = [
    path('feeds/', feeds, name='profile_app-feeds'),
    path('home/', home, name='profile_app-home'),
    path('settings/', settings, name='profile_app-settings'),
    path('update-profile/', update_profile, name='profile_app-update-profile'),
    path('add-post/', add_post, name='profile_app-add-post'),
    path('search-user/', search_user, name='profile_app-search-user'),
    path('follow-user/', follow_user, name='profile_app-follow-user'),
    path('like-post/', like_post, name='profile_app-like-post'),
    path('unfollow-user/', unfollow_user, name='profile_app-unfollow-user'),
    path("delete-post", delete_post, name='profile_app-delete-post')
]

profile_app/models.py
from django.db import models
from django.contrib.auth.models import User


def profile_photo_upload_to(instance, filename):
    return f"profile_photos/user_{instance.user.id}/{filename}"


def post_photos_upload_to(instance, filename):
    return f"post_photos/user_{instance.profile.user.id}/{filename}"


class Profile(models.Model):
    choices = [('M', 'Male'),
               ('F', 'Female'),
               ('O', 'Others')]

    user = models.OneToOneField(to=User, on_delete=models.CASCADE, related_name='user_profile')
    profile_photo = models.ImageField(upload_to=profile_photo_upload_to, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    gender = models.CharField(max_length=4, choices=choices, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    following = models.ManyToManyField(to=User, related_name='following')
    followers = models.ManyToManyField(to=User, related_name='followers')

    class Meta:
        db_table = 'profile'


class Post(models.Model):
    profile = models.ForeignKey(to=Profile, related_name='profile_post', on_delete=models.CASCADE)
    post_photo = models.ImageField(upload_to=post_photos_upload_to, blank=True, null=True)
    is_video = models.BooleanField(default=False)
    caption = models.TextField(blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(to=Profile)

    class Meta:
        db_table = 'post'
        ordering = ['-date_added']

profile_app/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponseForbidden
from profile_app.models import Profile, Post
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib import messages


def paginated_results(user_obj, num):
    x = Post.objects.filter(profile__user__in=user_obj.user_profile.following.all())
    p = Paginator(x, 3)
    return p.page(num)


def feeds(request):
    if request.user.is_authenticated:
        page_num = request.GET.get('page', default=1)
        context = {'profile_photo': request.user.user_profile.profile_photo,
                   'full_name': request.user.get_full_name()}

        current_page = paginated_results(request.user, page_num)
        context['current_page'] = current_page
        if len(current_page.object_list) == 0:
            context['is_list_empty'] = True

        if request.user.user_profile.description is not None:
            context['description'] = request.user.user_profile.description
        return render(request, 'feed.html', context=context)
    return HttpResponseRedirect(redirect_to=reverse('auth_app-login'))


def posts_restructured(user_obj):
    posts = list(user_obj.user_profile.profile_post.all())
    b = [tuple(posts[i:i + 3]) for i in range(0, len(posts), 3)]
    return b


def home(request):
    if request.user.is_authenticated:
        context = {'username': request.user.get_username(),
                   'profile_photo': request.user.user_profile.profile_photo,
                   'full_name': request.user.get_full_name(),
                   'all_posts': posts_restructured(request.user),
                   'following': request.user.user_profile.following.all(),
                   'followers': request.user.user_profile.followers.all()}

        if request.user.user_profile.description is not None:
            context['description'] = request.user.user_profile.description

        return render(request, 'home.html', context=context)
    return HttpResponseRedirect(redirect_to=reverse('auth_app-login'))


def settings(request):
    if request.user.is_authenticated:
        context = {'first_name': request.user.first_name,
                   'last_name': request.user.last_name,
                   'email': request.user.email,
                   'username': request.user.get_username()}
        return render(request, 'settings.html', context=context)
    return HttpResponseRedirect(redirect_to=reverse('auth_app-login'))


def update_profile(request):
    if request.method == 'POST':
        profile_photo_ = request.FILES.get('profile_photo')
        description_ = request.POST['description']
        gender_ = request.POST['gender']
        dob_ = request.POST['dob']

        profile = Profile.objects.get(user=request.user)

        profile.description = description_
        profile.gender = gender_
        profile.dob = dob_

        if profile_photo_:
            profile.profile_photo = profile_photo_

        profile.save()
        return HttpResponseRedirect(redirect_to=reverse('profile_app-home'))
    return HttpResponseForbidden(content='Invalid response')


def validate_post(name: str):
    extension = name.split('.')[1]
    if extension in ('jpg', 'png'):
        video = False
        return video
    elif extension in ('mp4', 'mov', 'avi', 'wmv'):
        video = True
        return video
    else:
        raise NameError('Improper File Format!')


def add_post(request):
    if request.method == "POST":
        try:
            image = request.FILES.get('image')
            is_video = validate_post(image.name)
            caption = request.POST['caption']
            Post.objects.create(profile=request.user.user_profile, post_photo=image, caption=caption, is_video=is_video)
        except Exception as e:
            messages.error(request, f"{e}")
        else:
            messages.success(request, "Post Created Successfully!")
        return HttpResponseRedirect(redirect_to=reverse('profile_app-feeds'))
    return HttpResponseForbidden(content='Invalid response')


def search_user(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            user = request.GET['user']
            all_users = User.objects.filter(username__icontains=user)
            context = {'users': all_users,
                       'self': request.user.user_profile.following.all()}
            return render(request, 'search_list.html', context=context)
        return HttpResponseForbidden(content='Invalid response')
    return HttpResponseRedirect(redirect_to=reverse('auth_app-login'))


def follow_user(request):
    if request.method == "POST":
        if request.POST['username'] != request.user.get_username():
            usr = User.objects.get(username=request.POST['username'])
            usr.user_profile.followers.add(request.user)
            request.user.user_profile.following.add(usr)
        return HttpResponseRedirect(redirect_to=reverse('profile_app-feeds'))
    return HttpResponseForbidden(content='Invalid response')


def unfollow_user(request):
    if request.method == "POST":
        usr = User.objects.get(username=request.POST['username'])
        usr.user_profile.followers.remove(request.user)
        request.user.user_profile.following.remove(usr)
        return HttpResponseRedirect(redirect_to=reverse('profile_app-feeds'))
    return HttpResponseForbidden(content='Invalid response')


def like_post(request):
    if request.method == 'POST':
        _id = request.POST['pid']
        post = Post.objects.get(id=_id)
        post.likes.add(request.user.user_profile)
        return HttpResponseRedirect(redirect_to=reverse('profile_app-feeds'))
    return HttpResponseForbidden(content='Invalid response')


def delete_post(request):
    if request.method == 'POST':
        post_id = request.POST['post_id']
        try:
            post = Post.objects.get(id=post_id)
        except Exception as e:
            return HttpResponseForbidden("Invalid Request")
        else:
            post.delete()
            return HttpResponseRedirect(redirect_to=reverse('profile_app-home'))
    return HttpResponseForbidden("Invalid response")

profile_app/templates/feed.html
{% extends 'landing.html' %}
{% load cache %}

{% block title %}Feed{% endblock %}

{% load humanize %}
{% block feed_change %}
    <div class="container">

    <div class="row" style="display: flex; justify-content: center; align-items: start">

        <div class="col-md-3">
            <div class="shadow">
                <div class="card mb-3">
                        <div class="card-body text-center">
                            {% if profile_photo != '' %}
                                <img src="{{ profile_photo.url }}" alt="User Profile Image" class="img-fluid rounded-circle" style="width: 96px; height: 90px">
                            {% else %}
                                {% load static %}
                                <img src="{% static 'blank-profile-picture.png' %}" alt="User Profile Image" class="img-fluid rounded-circle" style="width: 96px; height: 90px">
                            {% endif %}
                            <hr style="color: #61b0a6">
                            <h5 class="card-title" style="color: #5b80b2">{{ full_name }}</h5>
                            <p class="card-text" style="font-size: 15px; font-family: sans-serif">{{ description }}</p>
                        </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="shadow">
                <div class="card text-center mb-3">
                    <div class="card-header" style="background-color: #c0e3d7"><h4>New Post</h4></div>
                        <div class="card-body">
                            {% if messages %}
                                {% for message in messages %}
                                    {% if message.tags == 'success' %}
                                        <p style="color: green; font-size: 14px;">{{ message }}</p>
                                    {% elif message.tags == 'error' %}
                                        <p style="color: red; font-size: 14px;">{{ message }}</p>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}

                            <form method="POST" action="{% url 'profile_app-add-post' %}" class="form-inline" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="What's on your mind?" name="caption" required>
                                </div>
                                <div class="row mt-2">
                                    <div class="col-sm-8">
                                        <div class="form-group">
                                            <input type="file" id="actual-btn" name="image" required hidden/>
                                            <label for="actual-btn"
                                                   style="display: inline-block;
                                                   background-color: #dbeaea;
                                                   padding: 0.5rem;
                                                   color: #25b5b5;
                                                   font-family: sans-serif;
                                                   border-radius: 0.3rem;
                                                   cursor: pointer;
                                                   margin-top: 5px">Choose File</label>
                                            <span id="file-chosen">No file chosen</span>
                                            <script>const actualBtn = document.getElementById('actual-btn');
                                                const fileChosen = document.getElementById('file-chosen');
                                                actualBtn.addEventListener('change', function(){
                                                  fileChosen.textContent = this.files[0].name
                                                })</script>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <button type="submit" class="btn rounded-pill btn-outline-info" style="margin-top: 5px">Post</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                </div>
            </div>

                    {% for post in current_page.object_list %}
                        <div class="shadow">
                            <div class="card text-left">
                                <div class="card-header" style="font-weight: bold; color: #5b80b2">@{{ post.profile.user.get_username }}</div>
                                {% if post.is_video %}
                                    <video src="{{ post.post_photo.url }}" controls></video>
                                {% else %}
                                    <img class="img-fluid" src="{{ post.post_photo.url }}" alt="post image">
                                {% endif %}
                                <div class="card-body">
                                    <div class="row">
                                    <form method="POST" action="{% url 'profile_app-like-post' %}">
                                        {% csrf_token %}
                                        <input type="hidden" value="{{ post.id }}" name="pid">
                                        <button type="submit" class="btn rounded-pill btn-outline-danger btn-sm">Like {{ post.likes.all.count }}</button><span style="margin-left: 10px">{{ post.caption }}</span>
                                    </form>

                                    </div>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">{{ post.date_added|naturaltime }}</small>
                                </div>
                            </div>
                        </div>
                        <br>
                    {% empty %}
                        <h5 class="text-center" style="color: #33544a">Not Following Anyone!</h5>
                    {% endfor %}
        </div>
    </div>
    </div>
    {% if not is_list_empty %}
    <div class="container" style="display: flex; justify-content: center; margin-top: 30px">
        <nav aria-label="Page navigation example">
              <ul class="pagination">
                  {% if current_page.has_previous %}
                      <li class="page-item">
                        <a class="page-link" href="{% url 'profile_app-feeds' %}?page={{ current_page.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                      </li>
                  {% else %}
                      <li class="page-item disabled">
                        <a class="page-link" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                      </li>

                  {% endif %}
                  <li class="page-item">
                      <a class="page-link">{{ current_page.number }}</a>
                  </li>
                  {% if current_page.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="{% url 'profile_app-feeds' %}?page={{ current_page.next_page_number }}" aria-label="Next">
                          <span aria-hidden="true">&raquo;</span>
                      </a>
                  </li>
                  {% else %}
                      <li class="page-item disabled">
                          <a class="page-link" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                          </a>
                      </li>
                  {% endif %}
              </ul>
        </nav>
    </div>
    {% endif %}
    <br>
{% endblock %}

profile_app/templates/home.html
{% extends 'landing.html' %}
{% load cache %}

{% block title %}Profile{% endblock %}

{% block feed_change %}
<div class="container" style="width: 1000px">
    <div class="row" style="display: flex; justify-content: space-evenly">
        <div class="col-sm-6">

        <div class="shadow">
            <div class="card mb-3">
                <div class="row g-0" style="align-items: center">
                    <div class="col-md-4">
                        <div class="container" style="display: flex; justify-content: center">
                            <div class="row">
                                {% if profile_photo != '' %}
                                    <a href="{{ profile_photo.url }}"><img src="{{ profile_photo.url }}" alt="Profile Photo" class="img-fluid rounded-circle" style="width: 96px; height: 90px; margin-top: 20px; margin-bottom: 20px"></a>
                                {% else %}
                                    {% load static %}
                                    <img src="{% static 'blank-profile-picture.png' %}" class="img-fluid rounded-circle" alt="Profile Photo" style="width: 96px; height: 90px; margin-top: 20px; margin-bottom: 20px">
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title text-center" style="color: darkcyan; font-family: sans-serif; font-weight: bold">{{ full_name }}</h5>
                            <hr>
                            <p class="card-text text-center">{{ description }}</p>


                            {% if request.user.username == username %}
                                <div class="row">
                                    <div class="col-sm-6" style="display: flex; justify-content: center; margin-bottom: 10px; margin-top: 10px">
                                            <button type="button" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#followingModal">Following</button>
                                    </div>
                                    <div class="col-sm-6" style="display: flex; justify-content: center; margin-top: 10px; margin-bottom: 10px">
                                        <button type="button" class="btn btn-outline-info" data-bs-toggle="modal" data-bs-target="#followersModal">Followers</button>
                                    </div>
                                </div>
                                <!-- Modal -->
                                <div class="modal fade" id="followingModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Users</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                      </div>
                                      <div class="modal-body">
                                        {% for usr in following %}
                                            <h5 class="text-center" style="color: #036262">{{ usr.get_username }}</h5>
                                            <hr>
                                        {% empty %}
                                            You are not following anyone.
                                        {% endfor %}
                                      </div>
                                    </div>
                                  </div>
                                </div>
{#                                ----#}
                                <div class="modal fade" id="followersModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                  <div class="modal-dialog">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Users</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                      </div>
                                      <div class="modal-body">
                                        {% for usr in followers %}
                                            <h5 class="text-center" style="color: #036262">{{ usr.get_username }}</h5>
                                            <hr>
                                        {% empty %}
                                            No Followers Yet.
                                        {% endfor %}
                                      </div>
                                    </div>
                                  </div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
            {% block all_posts %}
                {% cache 300 all__posts all_posts %}
            <h3 class="text-center" style="padding-top: 5px; padding-bottom: 10px">Posts</h3>

            {% for posts in all_posts %}
                <div class="row">
                {% for post in posts %}
                    <div class="col" style="align-items: center; margin: 5px">
                        <div class="row" style="">
                            {% if post.is_video %}
                                <img src="{% static 'thumbnail.png' %}" alt="thumbnail" style="height: 128px; width: 198px">
                            {% else %}
                                <img src="{{ post.post_photo.url }}" class="card-img" alt="Stony Beach" style="width: 194px; height: 128px"/>
                            {% endif %}
                        </div>
{#                        <div class="container" style="margin-top: 10px; justify-content: center">#}
                            <button type="button" class="btn rounded-pill btn-outline-danger btn-sm" style="margin-top: 12px" data-bs-toggle="modal" data-bs-target="#exampleModal{{ post.id }}">View Post</button>
{#                        </div>#}
                        <div class="modal fade" id="exampleModal{{ post.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">@{{ username }}</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        {% if post.is_video %}
                                            <video src="{{ post.post_photo.url }}" controls style="width: 470px; height: 300px"></video>
                                        {% else %}
                                            <img src="{{ post.post_photo.url }}" class="card-img" alt="Stony Beach"/>
                                        {% endif %}
                                    <p style="margin-top: 5px; font-family: sans-serif; font-weight: bold">{{ post.caption }}</p>
                                    <p>Likes: {{ post.likes.all.count }}</p>
                                    </div>
                                    <div class="modal-footer">
                                        <form method="POST" action="{% url 'profile_app-delete-post' %}">
                                            {% csrf_token %}
                                            <input value="{{ post.id }}" name="post_id" type="hidden">
                                            <button type="submit" class="btn btn-outline-danger">Delete Post</button>
                                        </form>
                                      </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                </div>
            {% empty %}
                <h5 class="text-center" style="color: #7f968d">No Post Added Yet!</h5>
            {% endfor %}

        </div>
                {% endcache %}
        {% endblock all_posts %}
        </div>

    </div>
{% endblock %}

profile_app/templates/settings.html
{% extends 'landing.html' %}

{% block title %}Settings{% endblock %}

{% block feed_change %}

    <div class="container" style="display: flex; justify-content: center; align-items: center;">
        <div class="shadow">
        <div class="card text-center" style="width: 25rem;">

            <div class="card-header" style="background-color: #c0e3d7">
                <h3>Profile Settings</h3>
            </div>

            <div class="card-body">

                <form method="POST" action="{% url 'profile_app-update-profile' %}" enctype="multipart/form-data">
                {% csrf_token %}
                      <div class="input-group mb-3">
                          <input type="file" class="form-control" accept="image/*" id="id_profile_photo" name="profile_photo">
                          <label class="input-group-text" for="id_profile_photo">Profile Photo</label>
                      </div>

                      <div class="mb-3">
                          <input class="form-control" placeholder="Tell us About Yourself" name="description" required>
                      </div>

                      <div class="mb-3">
                          <select class="form-select form-select-sm" aria-label="Small select example" name="gender" required>
                              <option selected value="">Select Gender</option>
                              <option value="M">Male</option>
                              <option value="F">Female</option>
                              <option value="O">Others</option>
                          </select>
                      </div>

                      <div class="mb-3">
                          <input type="text" class="form-control" name="first_name" placeholder="{{ first_name }}" disabled>
                      </div>

                      <div class="mb-3">
                          <input type="text" class="form-control" name="last_name" placeholder="{{ last_name }}" disabled>
                      </div>

                      <div class="mb-3">
                          <input type="text" class="form-control" placeholder="{{ username }}" disabled>
                      </div>

                      <div class="mb-3">
                          <input type="email" class="form-control" name="email" placeholder="{{ email }}" disabled>
                      </div>

                      <div class="mb-3">
                          <input type="date" class="form-control" name="dob" required>
                      </div>

                      <button type="submit" class="btn btn-outline-info">Update</button>
                </form>

            </div>
        </div>
        </div>
    </div>


{% endblock %}